version: '3.9'

services:
  mongodb-temporalight:
    container_name: 'mongodb_temporalight'
    image: mongodb/mongodb-community-server:${MONGODB_VERSION}
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
